name: puhala.com
favicon: null
layout_spectrum: 0.3937
typography_spectrum: 0.9466083110310137
title: Michael Puhala Musings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e4e8eb'
    - '#c0bbbf'
    - '#5d5155'
    - '#5e9ba3'
  brandStrength: 0.29505862831138074
  lightness: 0.6019515316002071
  saturation: 0.4044258603826165
  rhythmicContrast: 0.1152208570856601
purpose: []
